### ISSUE TITLE
App Crashes on launching

### ISSUE THREAD

**Issue by neupanedipen** [demistry/MedManager#1]
#### Expected behavior<br>
The app is supposed to be stable and should work on launch.<br>
#### Actual behavior<br>
But the app crashes immediately after launchinf.<br>
#### How to reproduce<br>
1. Install the app from apk file provided on the readme of the repository in github.<br>
2. Launch the app.<br>
3. The app crashes.<br>
* Device: Samsung Galaxy J5<br>
* Operating System: Android 6.0.1<br>
#### Recording Of The Bug<br>
https://youtu.be/Ji-_ISvSi54

**Comment by demistry** [comment]
Please do well to check the uploaded video. Its not from the Med Manager app

**Comment by neupanedipen** [comment]
I am extremely sorry. Have updated the video link please have a look.

**Comment by demistry** [comment]
Download the app again, it has been resolved.
