### ISSUE TITLE
logo suggestion free for u

### ISSUE THREAD

**Issue by abdulmalikkhan655** [demistry/MedManager#2]
hello,  @demistry   i  want to designed a new logo for "MedManager" and it's free.
 if you give  me permission i will send you  my design

**Comment by demistry** [comment]
@abdulmalikkhan655 Yes please go ahead. It will be very much appreciated.

**Comment by abdulmalikkhan655** [comment]
Thanks sir today i will send you logo preview as soon as

**Comment by demistry** [comment]
No problem. Thank you very much
